# Generated by Django 5.0 on 2023-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Type', models.CharField(max_length=25)),
                ('Product_Name', models.CharField(max_length=25)),
                ('Product_Size', models.IntegerField()),
                ('Product_Price', models.FloatField()),
            ],
        ),
    ]
