# Generated by Django 5.0 on 2023-12-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Size',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='images/', verbose_name='Product Image')),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Genesis.product')),
            ],
        ),
    ]
