# Generated by Django 5.0 on 2023-12-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genesis', '0002_alter_product_product_size_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='Product_Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
