# Generated by Django 5.0 on 2023-12-21 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genesis', '0003_alter_product_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='Product_Image',
            field=models.ImageField(upload_to='images/', width_field='45px'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='Product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Genesis.product'),
        ),
    ]
